import type { Metadata } from "next";
import "./globals.css";
import { neueMontreal } from "./localFonts/neueMontreal";
import { Lato } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--lato",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${neueMontreal.variable} ${lato.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
