import type { Metadata } from "next";
import "./globals.css";
import { neueMontreal } from "./localFonts/neueMontreal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${neueMontreal.variable} antialiased font-sans`}>
        {children}
      </body>
    </html>
  );
}
